branches:
  only:
    - main
language: node_js
node_js:
  - 13

services:
  - docker

script:
## Build
  - docker-compose -f docker-compose-build.yaml build
## Tagging
  - docker tag udagram-api-feed phamthao/udagram-api-feed:latest
  - docker tag udagram-api-user phamthao/udagram-api-user:latest
  - docker tag udagram-frontend phamthao/udagram-frontend:latest
  - docker tag reverseproxy phamthao/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
## Push
  - docker push phamthao/udagram-api-feed
  - docker push phamthao/udagram-api-user
  - docker push phamthao/udagram-frontend
  - docker push phamthao/reverseproxy